name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
        targets: wasm32v1-none

    - name: Cache Rust
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: "ci"
        cache-on-failure: true

    - name: Install just
      uses: extractions/setup-just@v2

    - name: Install Stellar CLI
      uses: stellar/stellar-cli@v23.1.4

    - name: Run checks
      run: just check